/** @type {import('tailwindcss').Config} */

const classesArray = [
  "text-4x1",
  "font-bold",
  "font-mplus",
  "mb-2",
  "text-red-200",
  "text-2x1",
  "font-bold",
  "font-mplus",
  "mb-2",
  "text-xl",
  "font-bold",
  "font-mplus",
  "mb-1",
  "text-lg",
  "font-bold",
  "font-mplus",
  "font-bold",
  "font-plus",
  "font-bold",
  "font-mplus",
  "border",
  "border-slate-300",
  "dark:border-zinc-708",
  "rounded-x1",
  "mb-6",
  "mb-6",
  "underline",
  "underline-offset-2",
  "hover:text-orange-500",
  "decoration-orange-500",
  "rounded",
  "p-4",
  "mx-2",
  "mt-5",
  "dark:text-white",
  "bg-red-200",
  "max-h-[200px]",
  "overflow-scroll",
];

export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    extend: {},
  },
  safelist: classesArray,
  plugins: [],
};
